import type { SessionConfig } from '../types';
import {
  FIVE_CHAR_FULL_RANK_LIMIT,
  FIVE_CHAR_TOP_100K_RANK_LIMIT,
  FULL_5_CHAR_NONWORD_COUNT,
  makeGeneratedErgonomicNonwordAlphabet
} from '../core/alphabet';

// Ergonomic 5-character CVCVC-style nonwords. Generated by ranking pronounceable
// candidates with the QWERTY effort model, excluding /usr/share/dict/words and
// first20hours/google-10000-english entries, then applying light diversity caps.
export const ERGONOMIC_NONWORD_5_STRINGS = [
  'gutug', 'tutug', 'gutut', 'tutut', 'futug', 'gutuf', 'gugug', 'tutuf', 'futut', 'kutug',
  'rutug', 'gutur', 'tugug', 'gugut', 'kutut', 'rutut', 'tutur', 'tugut', 'futuf', 'gutij',
  'fugug', 'guguf', 'gurug', 'kutuf', 'rutuf', 'futur', 'tutij', 'dutug', 'gutud', 'tuguf',
  'fugut', 'kugug', 'gitug', 'gutig', 'turug', 'gurut', 'rugug', 'gugur', 'kutur', 'tutud',
  'dutut', 'gutih', 'kugut', 'tutig', 'gitut', 'rutur', 'turut', 'lutug', 'rugut', 'tugur',
  'titug', 'gutit', 'gutuk', 'futij', 'fuguf', 'furug', 'tutih', 'yerug', 'yetug', 'herug',
  'hetug', 'lutut', 'titut', 'tutit', 'tutuk', 'kutij', 'dutuf', 'futud', 'kuguf', 'serug',
  'setug', 'futig', 'gituf', 'furut', 'kurug', 'rutij', 'fitug', 'gigug', 'ruguf', 'fugur',
  'werug', 'wetug', 'rurug', 'yerut', 'yetut', 'litug', 'dugug', 'herut', 'hetut', 'jitug',
  'kutud', 'futih', 'setut', 'kutig', 'kurut', 'rutud', 'dutur', 'fitut', 'lutuf', 'gigut',
  'kugur', 'futit', 'gitur', 'rutig', 'tituf', 'werut', 'wetut', 'rurut', 'futuk', 'litut',
  'dugut', 'tigug', 'rugur', 'rerug', 'retug', 'ritug', 'sasas', 'jitut', 'lugug', 'yeruf',
  'yetuf', 'hasas', 'kutih', 'sutug', 'heruf', 'hetuf', 'jerug', 'jetug', 'rutih', 'ferug',
  'fetug', 'kutit', 'kutuk', 'lutur', 'tigut', 'dasas', 'fasas', 'rerut', 'retut', 'ritut',
  'sasad', 'rutit', 'titur', 'seruf', 'setuf', 'rutuk', 'fituf', 'lugut', 'dutij', 'hitug',
  'giguf', 'weruf', 'wetuf', 'hasad', 'gitij', 'lituf', 'duguf', 'figug', 'sutut', 'durug',
  'girug', 'jerut', 'jetut', 'ligug', 'yerur', 'yetur', 'jituf', 'ferut', 'fetut', 'herur',
  'hetur', 'jigug', 'wutug', 'dasad', 'fasad', 'saser', 'yegug', 'hegug', 'yitug', 'hitut',
  'giyer', 'yefug', 'dutud', 'haser', 'serur', 'setur', 'hefug', 'figut', 'dutig', 'gitud',
  'durut', 'fitur', 'tiguf', 'gigur', 'butug', 'lutij', 'gitig', 'reruf', 'retuf', 'rituf',
  'girut', 'werur', 'wetur', 'ligut', 'titij', 'ditug', 'litur', 'dugur', 'sasef', 'luguf',
  'segug', 'lurug', 'rigug', 'terug', 'tetug', 'tirug', 'jigut', 'wutut', 'yerer', 'yeyer',
  'daser', 'faser', 'jitur', 'sefug', 'giyef', 'herer', 'heyer', 'sutuf', 'hasef', 'wegug',
  'gerug', 'getug', 'yegut', 'jeruf', 'jetuf', 'hegut', 'jasas', 'yitut', 'wefug', 'yerij',
  'yetij', 'yefut', 'feruf', 'fetuf', 'herij', 'hetij', 'dutih', 'gotug', 'hefut', 'gitih',
  'sugug', 'butut', 'tiyer', 'seyer', 'ditut', 'dasef', 'fasef', 'lutud', 'dutit', 'titud',
  'dutuk', 'segut', 'lutig', 'lurut', 'hituf', 'rigut', 'tigur', 'titig', 'gasas', 'rerur',
  'retur', 'ritur', 'sadas', 'terut', 'tetut', 'tirut', 'werer', 'weyer', 'serij', 'setij',
  'sefut', 'figuf', 'sadug', 'lugur', 'higug', 'fitij', 'wegut', 'gerut', 'getut', 'hadas',
  'jasad', 'liguf', 'werij', 'sasey', 'wetij', 'wefut', 'tiyef', 'sutur', 'seref', 'litij',
  'seyef', 'saseh', 'hadug', 'firug', 'gotut', 'vutug', 'regug', 'pitug', 'jerur', 'jetur',
  'jiguf', 'wutuf', 'sugut', 'refug', 'lirug', 'hasey', 'ferur', 'fetur', 'jitij', 'haseh',
  'kerug', 'ketug', 'lutih', 'totug', 'titih', 'jirug', 'yituf', 'dadas', 'fadas', 'gasad',
  'sadad', 'sasah', 'saset', 'dadug', 'fadug', 'jegug', 'fiyer', 'sadut', 'wugug', 'higut',
  'yigug', 'fegug', 'lutit', 'hitur', 'jefug', 'saseg', 'kotug', 'butuf', 'hadad', 'hasah',
  'rerer', 'reyer', 'lutuk', 'fitud', 'dasey', 'fasey', 'haset', 'jaser', 'liyer', 'fefug',
  'dituf', 'daseh', 'faseh', 'figur', 'fitig', 'firut', 'hadut', 'vutut', 'regut', 'litud',
  'riguf', 'haseg', 'teruf', 'tetuf', 'pitut', 'sasaf', 'digug', 'ligur', 'rerij', 'retij',
  'ritij', 'jiyer', 'litig', 'refut', 'lirut', 'bugug', 'jitud', 'kerut', 'ketut', 'gokug',
  'fiyef', 'geruf', 'getuf', 'safug', 'rirug', 'jerer', 'jeyer', 'jigur', 'dadad', 'dasah',
  'fadad', 'fasah', 'hasaf', 'totut', 'wutur', 'jitig', 'daset', 'faset', 'gaser', 'jirut',
  'sasug', 'ferer', 'feyer', 'jasef', 'liyef', 'sutij', 'gotuf', 'dadut', 'fadut', 'jegut',
  'jotug', 'wugut', 'gogug', 'hafug', 'yigut', 'putug', 'fegut', 'daseg', 'faseg', 'yitur',
  'suguf', 'jerij', 'jetij', 'jefut', 'kotut', 'hasug', 'fotug', 'surug', 'ferij', 'fetij',
  'jiyef', 'fefut', 'fitih', 'potug', 'butur', 'dasaf', 'fasaf', 'riyer', 'litih', 'digut',
  'ditur', 'gasef', 'ritud', 'higuf', 'bugut', 'gokut', 'dafug', 'fafug', 'rigur', 'hitij',
  'jitih', 'ritig', 'rirut', 'terur', 'tetur', 'dasug', 'fasug', 'vutuf', 'hirug', 'sutud',
  'gerur', 'getur', 'jotut', 'gogut', 'pituf', 'jadas', 'putut', 'tokug', 'riyef', 'sutig',
  'fotut', 'surut', 'jadug', 'gotur', 'tegug', 'keruf', 'ketuf', 'pigug', 'situg', 'totuf',
  'kasas', 'potut', 'sugur', 'tefug', 'wutij', 'togug', 'kokug', 'vugug', 'jaseh', 'gegug',
  'wuguf', 'yiguf', 'rotug', 'hiyer', 'ritih', 'wurug', 'gefug', 'gadas', 'kotuf', 'yitij',
  'kogug', 'gadug', 'hitud', 'higur', 'hitig', 'yirug', 'hirut', 'terer', 'jadad', 'jasah',
  'teyer', 'butij', 'gasey', 'jaset', 'diguf', 'sutih', 'tokut', 'gaseh', 'ditij', 'jadut',
  'vutur', 'tegut', 'buguf', 'gokuf', 'gerer', 'geyer', 'pigut', 'burug', 'jaseg', 'kasad',
  'pitur', 'jokug', 'hiyef', 'situt', 'terij', 'tetij', 'dirug', 'tefut', 'sutit', 'togut',
  'kokut', 'vugut', 'fokug', 'sutuk', 'wutud', 'gegut', 'bitug', 'kerur', 'ketur', 'hotug',
  'jotuf', 'goguf', 'gerij', 'getij', 'putuf', 'wutig', 'gadad', 'gasah', 'jasaf', 'totur',
  'yiyer', 'rotut', 'wurut', 'gefut', 'gaset', 'jogug', 'pokug', 'fotuf', 'kogut', 'yitud',
  'gadut', 'fogug', 'gotij', 'wugur', 'hitih', 'jafug', 'yigur', 'witug', 'gaseg', 'potuf',
  'yitig', 'yirut', 'kotur', 'jasug', 'kegug', 'diyer', 'yasas', 'pogug', 'butud', 'pugug',
  'jagug', 'kefug', 'ditud', 'butig', 'kaser', 'digur', 'jokut', 'yiyef', 'ditig', 'dirut',
  'lerug', 'letug', 'fokut', 'bitut', 'bugur', 'wutih', 'hotut', 'jogut', 'tokuf', 'pokut',
  'diyef', 'kerer', 'keyer', 'fogut', 'vutij', 'piguf', 'yotug', 'jotur', 'yitih', 'rasas',
  'putur', 'wutit', 'witut', 'situf', 'wasas', 'pitij', 'rokug', 'wutuk', 'yasad', 'fotur',
  'kasef', 'kegut', 'toguf', 'kokuf', 'pogut', 'vuguf', 'vurug', 'pugut', 'kerij', 'ketij',
  'sigug', 'butih', 'pirug', 'kefut', 'dotug', 'rotuf', 'potur', 'totij', 'ditih', 'rogug',
  'koguf', 'lerut', 'letut', 'torug', 'butit', 'butuk', 'kotij', 'vitug', 'bufug', 'korug',
  'rasad', 'piyer', 'yotut', 'wasad', 'hokug', 'jokuf', 'vutud', 'rokut', 'tokur', 'yaser',
  'pitud', 'bituf', 'vutig', 'vurut', 'pigur', 'sigut', 'hotuf', 'pitig', 'kadas', 'pirut',
  'dotut', 'situr', 'hogug', 'joguf', 'pokuf', 'kadug', 'rogut', 'togur', 'kokur', 'bigug',
  'vugur', 'totud', 'jotij', 'totig', 'wituf', 'rotur', 'koyer', 'putij', 'kasey', 'piyef',
  'kaseh', 'poguf', 'kogur', 'yasef', 'kotud', 'puguf', 'wigug', 'jorug', 'vitut', 'purug',
  'potij', 'waser', 'hokut', 'yutug', 'leruf', 'letuf', 'vutih', 'porug', 'pitih', 'kadad',
  'kasah', 'lasas', 'kaset', 'jokur', 'yokug', 'hogut', 'kadut', 'bigut', 'vutit', 'bitur',
  'joyer', 'vutuk', 'kaseg', 'yotuf', 'hotur', 'jutug', 'dokug', 'jogur', 'yogug', 'rokuf',
  'rasef', 'pokur', 'jotud', 'wasef', 'putud', 'tasas', 'nerug', 'netug', 'wigut', 'siguf',
  'putig', 'kasaf', 'poyer', 'purut', 'witur', 'dotuf', 'sitij', 'yadas', 'dogug', 'roguf',
  'pogur', 'yutut', 'potud', 'yadug', 'pugur', 'kafug', 'sirug', 'lasad', 'rotij', 'kasug',
  'yokut', 'yasey', 'lerur', 'letur', 'yaseh', 'vituf', 'rorug', 'jutut', 'hokuf', 'dokut',
  'yogut', 'tasad', 'vigug', 'nerut', 'netut', 'putih', 'mitug', 'radas', 'yotur', 'siyer',
  'wadas', 'legug', 'yadad', 'yasah', 'rokur', 'yaset', 'hoguf', 'radug', 'dogut', 'wadug',
  'biguf', 'lefug', 'situd', 'bitij', 'yadut', 'sigur', 'putit', 'royer', 'sitig', 'dotur',
  'sirut', 'hotij', 'rasey', 'putuk', 'wasey', 'yaseg', 'raseh', 'rogur', 'waseh', 'rotud',
  'birug', 'wiguf', 'horug', 'nasas', 'witij', 'yasaf', 'siyef', 'yutuf', 'lerer', 'leyer',
  'taser', 'vigut', 'vitur', 'nitug', 'wirug', 'radad', 'mitut', 'wadad', 'wasah', 'yafug',
  'waset', 'legut', 'hokur', 'yokuf', 'lasef', 'yasug', 'lerij', 'letij', 'wadut', 'biyer',
  'lefut', 'sotug', 'sitih', 'hoyer', 'waseg', 'yugug', 'bitud', 'jutuf', 'vasas', 'dokuf',
  'hogur', 'yoguf', 'hotud', 'bigur', 'merug', 'metug', 'neruf', 'netuf', 'bitig', 'birut',
  'tasef', 'nasad', 'wiyer', 'wasaf', 'yotij', 'doguf', 'witud', 'botug', 'wigur', 'yorug',
  'jugug', 'biyef', 'wafug', 'witig', 'nitut', 'wirut', 'dotij', 'wasug', 'yutur', 'perug',
  'petug', 'dorug', 'sotut', 'ladas', 'wiyef', 'yugut', 'yokur', 'vasad', 'ladug', 'verug',
  'vetug', 'bitih', 'viguf', 'merut', 'metut', 'vitij', 'yoyer', 'naser', 'mituf', 'lasey',
  'jutur', 'laseh', 'dokur', 'yogur', 'tadas', 'yotud', 'nerur', 'netur', 'virug', 'migug',
  'botut', 'witih', 'wotug', 'tadug', 'jugut', 'doyer', 'dogur', 'dotud', 'tasey', 'taseh',
  'ladad', 'lasah', 'perut', 'petut', 'laset', 'hutug', 'nasef', 'negug', 'vaser', 'ladut',
  'verut', 'vetut', 'nefug', 'masas', 'viyer', 'laseg', 'nituf', 'sokug', 'vitud', 'yutij',
  'vigur', 'nigug', 'vitig', 'virut', 'zerug', 'zetug', 'migut', 'sotuf', 'lasaf', 'wotut',
  'mitur', 'yuguf', 'sogug', 'nerer', 'neyer', 'vasef', 'meruf', 'metuf', 'lafug', 'bokug',
  'viyef', 'basas', 'kitug', 'lasug', 'hutut', 'jutij', 'negut', 'votug', 'lagug', 'masad',
  'nerij', 'netij', 'botuf', 'nefut', 'nadas', 'juguf', 'berug', 'betug', 'bogug', 'sokut'
] as const;

export const ergonomicNonword5CharConfig: SessionConfig = {
  condition_id: 'five_char_ergonomic_nonwords_n1000',
  alphabet: [...ERGONOMIC_NONWORD_5_STRINGS],
  input_modality: 'keyboard',
  scoring: {
    mode: 'exact_match',
    advance_on_error: true
  },
  display: {
    show_current_target: true,
    show_next_target: false,
    show_keyboard_overlay: false,
    require_space: true
  },
  duration_seconds: 60,
  familiarization_seconds: 20
};

export const ergonomicNonword5CharN100kConfig: SessionConfig = {
  condition_id: 'five_char_ergonomic_nonwords_n100000',
  generated_alphabet: makeGeneratedErgonomicNonwordAlphabet(5, 100_000, FIVE_CHAR_TOP_100K_RANK_LIMIT),
  input_modality: 'keyboard',
  scoring: {
    mode: 'exact_match',
    advance_on_error: true
  },
  display: {
    show_current_target: true,
    show_next_target: false,
    show_keyboard_overlay: false,
    require_space: true
  },
  duration_seconds: 60,
  familiarization_seconds: 20
};

export const ergonomicNonword5CharAllConfig: SessionConfig = {
  condition_id: `five_char_ergonomic_nonwords_n${FULL_5_CHAR_NONWORD_COUNT}`,
  generated_alphabet: makeGeneratedErgonomicNonwordAlphabet(5, FULL_5_CHAR_NONWORD_COUNT, FIVE_CHAR_FULL_RANK_LIMIT),
  input_modality: 'keyboard',
  scoring: {
    mode: 'exact_match',
    advance_on_error: true
  },
  display: {
    show_current_target: true,
    show_next_target: false,
    show_keyboard_overlay: false,
    require_space: true
  },
  duration_seconds: 60,
  familiarization_seconds: 20
};
